# Generated by Django 3.2.10 on 2021-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211215_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False, help_text="By signing up you consent to our <a href='/privacy/'>privacy agreement</a> and <a href='/terms/'>terms of use</a>."),
        ),
    ]
