# Generated by Django 3.2.10 on 2021-12-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
