# Generated by Django 3.2.10 on 2021-12-17 16:55

import coinginie.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='doc',
            field=models.ImageField(blank=True, upload_to=coinginie.users.models.user_doc),
        ),
    ]
