# Generated by Django 3.2.10 on 2021-12-18 02:30

import coinginie.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_investor_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='doc',
            field=models.FileField(blank=True, upload_to=coinginie.users.models.user_doc),
        ),
    ]
