# Generated by Django 3.2.10 on 2021-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_investor_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='investor_id',
        ),
        migrations.AddField(
            model_name='user',
            name='investor_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
