# Generated by Django 3.2.10 on 2021-12-18 17:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211218_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg: +18012345678', max_length=128, region=None),
        ),
    ]
