# Generated by Django 3.2.10 on 2021-12-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_investor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
