# Generated by Django 3.2.10 on 2021-12-18 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211218_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='account_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='routing_no',
            field=models.CharField(blank=True, help_text='must be the recipients 9 digits routing number', max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')], verbose_name='Recipient Routing Number'),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')]),
        ),
    ]
