# Generated by Django 3.2.10 on 2021-12-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='features',
            field=models.TextField(),
        ),
    ]
