# Generated by Django 3.2.10 on 2021-12-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_plans_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontract', to='contracts.subscription'),
        ),
    ]
