# Generated by Django 3.2.10 on 2021-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='icon',
            field=models.CharField(choices=[('bx-walk', 'WALK'), ('bx-run', 'RUN'), ('bx-cycling', 'BICYCLE'), ('bx-car', 'CAR')], max_length=250, null=True),
        ),
    ]
