# Generated by Django 3.2.10 on 2021-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='total_investment',
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
