# Generated by Django 3.2.10 on 2021-12-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='exh_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exchrate', to='wallet.exchangerate'),
        ),
    ]
