# Generated by Django 3.2.10 on 2021-12-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_exh_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='verified',
        ),
    ]
