# Generated by Django 3.2.10 on 2021-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_deposit_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
