# Generated by Django 3.2.10 on 2021-12-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_deposit_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='exh_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invrate', to='wallet.exchangerate'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='exh_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deprate', to='wallet.exchangerate'),
        ),
    ]
