# Generated by Django 3.2.10 on 2021-12-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20211218_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='exh_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tranrate', to='wallet.exchangerate'),
        ),
    ]
