# Generated by Django 3.2.10 on 2021-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transactions_exh_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
